queue_rules:
  - name: renovate
    queue_conditions:
      - author=renovate[bot]
      - label!=no-mergify
      - "#changes-requested-reviews-by=0"
    merge_conditions: []
    merge_method: rebase
  - name: default
    queue_conditions:
      - label!=no-mergify
      - '#approved-reviews-by>=1'
    merge_conditions: []
    merge_method: rebase

pull_request_rules:
  - name: default + renovate
    conditions: []
    actions:
      queue:
priority_rules:
  - name: priority for queue `renovate`
    conditions:
      - author=renovate[bot]
      - "#changes-requested-reviews-by=0"
    priority: 2250
